Added Hashicorp Consul cookbook
aashishmodak/cookbooksrepo pull request #7
Opened 2017-08-02 07:42 UTC by RajeshwariMakond

Added Hashicorp Consul cookbook

2017-08-06 07:50 UTC, aashishmodak commented on hconsul/metadata.rb
> +maintainer 'The Authors'
Add your name as maintainer

2017-08-06 07:50 UTC, aashishmodak commented on hconsul/metadata.rb
> +maintainer_email 'you@example.com'
Add your email id

2017-08-06 07:50 UTC, aashishmodak commented on hconsul/metadata.rb
> +# issues_url 'https://github.com/<insert_org_here>/hconsul/issues'
update issue url

2017-08-06 07:50 UTC, aashishmodak commented on hconsul/metadata.rb
> +# source_url 'https://github.com/<insert_org_here>/hconsul'
update source url

2017-08-06 07:51 UTC, aashishmodak commented
Why do you need this file "hconsul/files/default/consul_0.9.0_linux_amd64/consul" ?

2017-08-06 07:53 UTC, aashishmodak commented on hconsul/README.md
> +TODO: Enter the cookbook description here.
It says description is TODO?

2017-08-06 08:04 UTC, aashishmodak commented on hconsul/README.md
> +TODO: Enter the cookbook description here.
refer readme from https://github.com/miketheman/nginx/tree/v2.6.0

2017-08-08 05:20 UTC, aashishmodak commented on hconsul/metadata.rb
> +issues_url 'https://github.com/aashishmodak/cookbooksrepo/SAPDRM-15_hconsul/hconsul/issues'
remove this word "SAPDRM-15_hconsul" from url

2017-08-08 05:20 UTC, aashishmodak commented on hconsul/metadata.rb
> +source_url 'https://github.com/aashishmodak/cookbooksrepo/SAPDRM-15_hconsul/hconsul'
remove this word "SAPDRM-15_hconsul" from url

2017-08-08 05:22 UTC, aashishmodak commented on README.md
> +Installs Hashicorp Consul on CentOS 7
You need to update the README for hconsul and not this one

2017-08-08 05:23 UTC, aashishmodak commented
"hconsul/files/default/consul_0.9.0_linux_amd64/consul" - this file is still in PR.

2017-08-08 06:58 UTC, aashishmodak requested changes
Fix the review comments and merge conflicts

2017-08-08 09:39 UTC, RajeshwariMakond commented
conflict merged please review

2017-08-08 09:55 UTC, aashishmodak requested changes
Do you need this file 
"hconsul/files/default/consul_0.9.0_linux_amd64/consul"

2017-08-09 04:55 UTC, aashishmodak commented
and resolve merge conflict

2017-08-10 05:02 UTC, aashishmodak commented on hconsul/nodes/ip-172-31-45-67.us-west-2.compute.internal.json
> +{
why do we need this file

2017-08-10 05:04 UTC, aashishmodak commented on hconsul/recipes/nodes/ip-172-31-45-67.us-west-2.compute.internal.json
> +{
why do we neeed this file?

2017-08-10 05:19 UTC, RajeshwariMakond commented
Please review

2017-08-10 05:20 UTC, RajeshwariMakond commented
Issue has been fixed, now can see only one file.Please review.

2017-08-10 05:49 UTC, closed without merging