Sapdrm 17 docker install
aashishmodak/cookbooksrepo pull request #8
Opened 2017-08-02 11:52 UTC by RajeshwariMakond

Added docker install cookbook

2017-08-06 08:08 UTC, aashishmodak commented on README.md
> +Added Hashicorp Consul cookbook
This is not consul, change this to docker

2017-08-06 08:08 UTC, aashishmodak commented on docker-install/README.md
> +TODO: Enter the cookbook description here.
add proper description, refer readme from https://github.com/miketheman/nginx/tree/v2.6.0

2017-08-06 08:08 UTC, aashishmodak commented on docker-install/metadata.rb
> +maintainer 'The Authors'
add your name as maintainer

2017-08-06 08:09 UTC, aashishmodak commented on docker-install/metadata.rb
> +maintainer_email 'you@example.com'
add your email as maintainer email

2017-08-06 08:09 UTC, aashishmodak commented on docker-install/metadata.rb
> +# issues_url 'https://github.com/<insert_org_here>/docker-install/issues'
update issue url

2017-08-06 08:09 UTC, aashishmodak commented on docker-install/metadata.rb
> +# source_url 'https://github.com/<insert_org_here>/docker-install'
update source url

2017-08-08 06:56 UTC, aashishmodak requested changes
Fix the review comments and merge conflict

2017-08-08 09:36 UTC, RajeshwariMakond commented
Resolved Conflict. Please review

2017-08-08 09:53 UTC, aashishmodak commented on docker-install/README.md
> +Installs Hashicorp vault from package OR source code to CentOS 7
This is not for Vault

2017-08-08 09:54 UTC, aashishmodak commented on docker-install/README.md
> +Installs Hashicorp vault on CentOS 7
Please correct the readme

2017-08-08 09:54 UTC, aashishmodak requested changes
Please correct readme

2017-08-08 10:29 UTC, aashishmodak approved these changes

2017-08-08 10:29 UTC, merged